new chapter_intro slides
ScPoEcon/ScPoEconometrics-Slides pull request #4
Opened 2020-01-16 10:39 UTC by gustavek

Hi Florian,

Here are our proposed slides for chapter_intro (I've renamed it to make it more explicit than chapter_1).
Because of large file issues I've had to zip "chapter_intro_files/figure-html/contours_iris_2015.zip" so the code for the map won't work unless you unzip that file. The spirit of the lecture has very much stayed the same, but there are some content changes nonetheless.

Feel free to disagree with any of them of course. If you think these slides are likely to take more than 2 hours to cover then I think it would be good to stop at slide 29.
Let us know what you think :)

Thanks!

I'll be making a PR for chapter_summarizing_data quickly.

Gustave

2020-01-16 11:00 UTC, floswald commented
thanks, i'll have a look! 

it's **not** a good idea to rename files. this way I cannot easily see changes you make. what you do when renaming a file is deleting `chapter1.Rmd` and creating a new file `chapter_intro.Rmd`. There is no diff between the two. I'd rather see each line you changed in `chapter1.Rmd`. makes sense? that's for future PRs! 

(we can change filenames as the very last step, if you have strong feelings between `chapter1.Rmd` and `chapter_intro.Rmd`).

2020-01-16 11:02 UTC, gustavek commented
I see, very sorry! I can create a new PR without the name change if you'd like!

2020-01-16 11:08 UTC, floswald commented
No big deal, if it’s too difficult it’s fine. For next time keep in mind!

On Thu 16 Jan 2020 at 12:02, gustavek <notifications@github.com> wrote:

> I see, very sorry! I can create a new PR without the name change if you'd
> like!
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/ScPoEcon/ScPoEconometrics-Slides/pull/4?email_source=notifications&email_token=AAHZM5SFVNWK3AAWPEMASBTQ6A5EDA5CNFSM4KHRYJV2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJDVI2Q#issuecomment-575100010>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHZM5WPEDIEUNLCI4OOYCTQ6A5EDANCNFSM4KHRYJVQ>
> .
>

2020-01-16 11:25 UTC, gustavek commented
I've renamed the folder and files and it seems to work. Will definitely keep it in mind!

2020-01-16 11:52 UTC, floswald commented
more things for next time:

* don't commit .html files. those are output
* don't commit anything other than source code (i.e. Rmd or the css if you change it) and stuff i need to compile the html (like new pictures etc)

2020-01-16 12:00 UTC, floswald requested changes
ok great! there is an issue with a wrong hard coded path, so i can't build this. can you change?

2020-01-16 12:00 UTC, floswald commented on chapter1/chapter1.Rmd
> +author: "Gustave Kenedi"
"Florian Oswald, Gustave Kenedi and Pierre Villedieu" seems more appropriate.

2020-01-16 12:00 UTC, floswald commented on chapter1/chapter1.Rmd
> +iris_shfl <- read_sf("chapter_intro_files/figure-html/contours_iris_2015/CONTOURS-IRIS.shp") %>%
broken path. you should at a minimum click "knit" on your computer before you send of the PR after you made changes.

2020-01-16 12:00 UTC, floswald commented on chapter1/chapter1.Rmd
> +  filter(dep == "75")
why don't you just create a new shapefile from this subset? that could then easily be included in ../rds

2020-01-16 12:00 UTC, floswald commented on chapter1/chapter1.Rmd
> +  filter(dep == "75")
load again paris subset shapefile from ../rds/

2020-01-17 09:13 UTC, floswald requested changes
great, almost there. the iris_inc file is missing.

2020-01-17 09:13 UTC, floswald commented on chapter1/chapter1.Rmd
>  iris_income <- readRDS("../rds/iris_inc.rds") %>%
`iris_inc.rds` is not there.

2020-01-17 13:53 UTC, floswald commented on chapter1/chapter1.Rmd
> +* Most of the time you will be cleaning data
You will spend a lot of time preparing data for further analysis.

2020-01-17 13:54 UTC, floswald commented on chapter1/chapter1.Rmd
> +```{r}
not visible on slide

2020-01-17 14:01 UTC, floswald requested changes
finally talking about content! 👍 looking good alreay. few remaining comments.

2020-01-17 14:01 UTC, floswald commented on chapter1/chapter1.Rmd
> +# geom_point(alpha = 0.7, show.legend = FALSE) +
i guess you want to show that?

2020-01-17 14:01 UTC, floswald commented on chapter1/chapter1.Rmd
> +knitr::include_graphics("chapter_intro_files/figure-html/rstudio.png")
wrong path

2020-01-17 14:01 UTC, floswald commented on chapter1/chapter1.Rmd
> +# Vectors => Comment: if you think this lecture up until now lasts more than 2 hours, I would be in favor of moving the rest of this lecture to Lecture 2/3.
i think we got to around here, maybe slightly further. why split the presentation though? it's not more *summary statistics* (topic of lecture 2) than the rest.

2020-01-17 14:01 UTC, floswald commented on chapter1/chapter1.Rmd
> +    murders$total_percap = murders$total / murders$population * 10000
consider adding brackets so it's clear what you multiply with 1000 here

2020-01-23 15:22 UTC, floswald requested changes
final comment to remove in `vectors` then this is ready.

2020-01-23 15:22 UTC, floswald commented on chapter1/chapter1.Rmd
> +# Vectors => Comment: if you think this lecture up until now lasts more than 2 hours, I would be in favor of moving the rest of this lecture to Lecture 2/3.
remove this comment in the heading and we are good to merge.

2020-01-23 15:43 UTC, gustavek commented
done :)

2020-01-23 15:45 UTC, merged