new diffindiff slides
ScPoEcon/ScPoEconometrics-Slides pull request #6
Opened 2020-01-20 17:57 UTC by gustavek

Hi Florian,

Here are our proposed slides for the new diff in diff lecture. I apologize in advance for having committed other files so you'll see 24 files changed, I hope this won't be too much of a hassle :/ Other than the .Rmd, there's only one other relevant image file: nj_penn_map.png.

For this lecture, I've taken the example of Card and Krueger (1994) on minimum wage's impact on employment to illustrate the DiD method. I've included two small tutorials for students using the actual data from the study to replicate some of the basic findings. I've tried to illustrate as best as possible how DiD works graphically and what the common trends assumption means.
Let me know what you think.

At the end of the lecture I have two slides for more advanced topics: multiperiod multistate extensions of DiD and standard error clustering (just the intuition, not the maths). I don't think it's necessary though the clustering may get students thinking about standard errors and not just point estimates which is important.
I assume we'll have to create a quiz with some questions on DiD. Duflo's (2001) paper (https://economics.mit.edu/files/726) could be used (other suggestions can be found here: https://twitter.com/i/moments/994859975968280576?lang=en).

Thanks!

I'll upload the new RDD slides very soon.

Gustave

2020-01-20 18:20 UTC, floswald commented
great! I will be able to look tomorrow or wednesday. just as a further idea, it might be cool to use those animations of nick nk. i just made a fork here https://github.com/ScPoEcon/causalgraphs checkout [the one on DiD](https://github.com/ScPoEcon/causalgraphs/blob/master/Animation%20of%20DID.R) which is a video [here](https://twitter.com/nickchk/status/1068215503762599936?s=20)

all of his animations are cool, so let's try to use as many as we can!

2020-01-20 21:21 UTC, gustavek commented
Thanks for the suggestion! We could make those animations with the real Card and Krueger (1994) data :)

2020-01-20 21:32 UTC, floswald commented
Good idea!

On Mon 20 Jan 2020 at 22:21, Gustave Kenedi <notifications@github.com>
wrote:

> Thanks for the suggestion! We could make those animations with the real
> Card and Krueger (1994) data :)
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/ScPoEcon/ScPoEconometrics-Slides/pull/6?email_source=notifications&email_token=AAHZM5RNT4KWLUNLPCSIIIDQ6YIWRA5CNFSM4KJH6RVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJN25DI#issuecomment-576433805>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHZM5XUUMEXOZ2UMOD3M3LQ6YIWRANCNFSM4KJH6RVA>
> .
>

2020-01-21 11:23 UTC, gustavek commented
A new update to `remark.js` has messed up how some of the slides are rendered (in particular, there is now a horizontal and/or vertical scrolling bar). The solution (as discussed [here](https://github.com/yihui/xaringan/issues/245)) appears to revert to the previous version of `remark.js` by adding the following code:
```{r}
output:
  xaringan::moon_reader:
    chakra: "https://cdnjs.cloudflare.com/ajax/libs/remark/0.14.0/remark.min.js"
```
It's probably not the ideal solution but it works.
Let me know if you also encounter the same issue and if this fix works on your end as well :)

2020-01-21 12:42 UTC, floswald commented
ok. linking to the previous version of remark.js seems the best solution to
me at the moment (I have not verified, but it seems clear there is an issue)

On Tue, 21 Jan 2020 at 12:23, Gustave Kenedi <notifications@github.com>
wrote:

> A new update to remark.js has messed up how some of the slides are
> rendered (in particular, there is now a horizontal and/or vertical
> scrolling bar). The solution (as discussed here
> <https://github.com/yihui/xaringan/issues/245>) appears to revert to the
> previous version of remark.js by adding the following code:
>
> output:
>   xaringan::moon_reader:
>     chakra: "https://cdnjs.cloudflare.com/ajax/libs/remark/0.14.0/remark.min.js"
>
> It's probably not the ideal solution but it works.
> Let me know if you also encounter the same issue and if this fix works on
> your end as well :)
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/ScPoEcon/ScPoEconometrics-Slides/pull/6?email_source=notifications&email_token=AAHZM5XW7RZMN2N5WXQQ55LQ63LLFA5CNFSM4KJH6RVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEJPM6MA#issuecomment-576638768>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAHZM5VEMSTVOH43WSKXSATQ63LLFANCNFSM4KJH6RVA>
> .
>

2020-01-22 08:27 UTC, floswald commented
Some more inspiration maybe 
https://blogs.worldbank.org/impactevaluations/revisiting-difference-differences-parallel-trends-assumption-part-i-pre-trend?cid=SHR_BlogSiteShare_EN_EXT

2020-01-24 17:03 UTC, floswald requested changes
beautiful, absolutely love it. those graphs are stunning. well done!

just some comments to work on. and please clean up the included files (there is some stuff from chapter 1 committed), so it will be difficult to merge. i left a comment how to do it.

2020-01-24 17:03 UTC, floswald commented on chapter_did/libs/remark-css/default.css
> +a, a > code {
why did you add this folder?

2020-01-24 17:03 UTC, floswald commented on chapter_did/chapter_did.html
> +<!DOCTYPE html>
don't commit html files please

2020-01-24 17:03 UTC, floswald commented on chapter_did/chapter_did.html
> +<!DOCTYPE html>
you can just delete locally and `git add` the deleted file

2020-01-24 17:03 UTC, floswald commented on chapter_did/chapter_did.Rmd
> +* Randomized control trials (RCTs) are the gold standard of causal identification
not sure what you want to say on this slide.
whether RCT's are *the gold standard* is a contentious discussion. more importantly, it means nothing to our students.
why is OLS not a *causal evaluation method*?
not really convinced by this slide.

2020-01-24 17:03 UTC, floswald commented on chapter_did/chapter_did.Rmd
> +* Seminal 1994 [paper](https://www.aeaweb.org/articles?id=10.1257/aer.20150355) by prominent labor economists David Card and Alan Krueger entitled "Minimum Wages and Employment: A Case Study of the F
wrong link

2020-01-24 17:03 UTC, floswald commented on chapter_did/chapter_did.Rmd
> +* Why is this not that straightforward? Why can't you just regress (un)employment rates on the level of the minimum wage?
too fast here. what you are saying about endogeneity is an additional problem i would not even mention. on this slide you should spell out which problem DiD solves for you. dont say "why can't you just reg u on minw", I don't think that is very clear. 
i would say: DiD allows you measure a causal effect by guiding you towards a suitable control group. you can *proxy* the non-treatment outcome Y^0 for treated units. you should refer back to the Roy model notation. DiD has the followign assumptions, etc

2020-01-24 17:03 UTC, floswald commented on chapter_did/chapter_did.Rmd
> +```
add: NJ and Penn are **similar**. similar habits, similar consumers, similar incomes, similar weather, similar everything.

2020-01-24 17:03 UTC, floswald commented on chapter_did/chapter_did.Rmd
> +library(diffindiff)
make sure output is visible or supress

2020-01-24 17:03 UTC, floswald commented on chapter_did/chapter_did.Rmd
> +ck_mw %>%
very nice 👌 table

2020-01-24 17:03 UTC, floswald commented on chapter_did/chapter_did.Rmd
> +
before that: 
* employment went down in PA from Feb to Nov 1992
* went up in NJ from Feb to Nov 1992

2020-01-24 17:03 UTC, floswald commented on chapter_did/chapter_did.Rmd
> +* Why is this not that straightforward? Why can't you just regress (un)employment rates on the level of the minimum wage?
it may be helpful to write down a slide with the assumptions on the OLS error term that underlie DID. like if

y_{it} = bo + b1X_{it} + u_{it} then

u_{it} = m_t + e_{it}

where m_t is a *macro trend* common to all units treated or not. set this up suitable with D notation so one sees that differencing gets rid of m?

2020-01-24 17:03 UTC, floswald commented on chapter_did/chapter_did.Rmd
> +# DiD Graphically
beautiful graph. amazing. ❤️

2020-01-24 17:03 UTC, floswald commented on chapter_did/chapter_did.Rmd
> +TREAT_s = \begin{cases}\begin{array}{lcl}
I prefer `\text{TREAT}_s` but that's just taste.

2020-01-24 17:03 UTC, floswald commented on chapter_did/chapter_did.Rmd
> +[\mathbb{E}(EMP_{st} \; | \; TREAT_s = 0, POST_t = 1)-\mathbb{E}(EMP_{st} \; | \; TREAT_s = 0, POST_t = 0)] = \delta$$
very good

2020-01-24 17:03 UTC, floswald commented on chapter_did/chapter_did.Rmd
> +# Multi-period DiD: Relaxing Common Trends Assumption => Too much?
yes :-)

2020-01-24 17:03 UTC, floswald commented on chapter_did/chapter_did.Rmd
> +# Clustered Standard Errors => Too much?
yes

2020-01-24 17:23 UTC, gustavek commented
Thanks for all the feedback and suggestions! I'll go over them this weekend (and take care of the git issues)!

2020-01-30 10:42 UTC, floswald commented on chapter_did/chapter_did.Rmd
> +* Randomized control trials (RCTs) are the gold standard of causal identification
This should be part of any such discussion. http://humcap.uchicago.edu/RePEc/hka/wpaper/Heckman_2020_randomization-soc-pol-revisited.pdf

2020-02-25 09:24 UTC, floswald commented
bumping that PR to see what's going on

2020-04-20 13:31 UTC, gustavek commented on chapter_did/chapter_did.Rmd
> +* Randomized control trials (RCTs) are the gold standard of causal identification
I've changed this part to say that multiple regression doesn't provide causal estimate most of the time because of selection on unobservables.

2020-04-20 13:32 UTC, gustavek commented on chapter_did/chapter_did.Rmd
> +* Why is this not that straightforward? Why can't you just regress (un)employment rates on the level of the minimum wage?
I've added a set of slides at the end formalizing the parallel trends assumption. took inspiration from http://economics.ozier.com/econ626/lec/econ626-L03-slides-2019.pdf and _Mostly Harmless Econometrics_. i think it's pretty understandable but maybe it's a bit too advanced?

2020-04-20 13:33 UTC, gustavek commented on chapter_did/chapter_did.Rmd
> +ck_mw %>%
Thanks!

2020-04-20 13:33 UTC, gustavek commented on chapter_did/chapter_did.Rmd
> +
The task that comes just before this slide essentially covers this and we can discuss it from the table no?

2020-04-20 13:33 UTC, gustavek commented on chapter_did/chapter_did.Rmd
> +# DiD Graphically
Thanks!

2020-04-20 13:38 UTC, floswald commented on chapter_did/chapter_did.Rmd
> +
still would be good to remind people of that important fact on the slide (after the task)

2020-04-20 13:56 UTC, floswald requested changes
few minor comments. overall *extremely* cool set of slides. Still love the graphs. good work.

2020-04-20 13:56 UTC, floswald commented on chapter_did/chapter_did.Rmd
> +## Today
? still missing?

2020-04-20 13:56 UTC, floswald commented on chapter_did/chapter_did.Rmd
>  remotes::install_github("b-rodrigues/diffindiff")
`remotes` output is too long and overwrites the right column. consider including that chunk twice, once run with hidden output (so no overwriting), and once with `eval=FALSE`

2020-04-20 13:56 UTC, floswald commented on chapter_did/chapter_did.Rmd
> +$$
i think this discussion is very good. take good time to explain that slowly. it's sufficiently easy to be understable I would say.

2020-04-20 17:50 UTC, gustavek commented on chapter_did/chapter_did.Rmd
> +## Today
adding it as we speak

2020-04-20 20:33 UTC, gustavek commented
Thanks for all your feedback and suggestions! @pvilledieu may make some other final changes to some of the graphs so let's keep the PR open just in case if you don't mind :)

2020-04-21 12:22 UTC, floswald commented
so this is good to merge?

2020-04-21 12:25 UTC, pvilledieu commented
Yes it’s good !

2020-04-21 12:25 UTC, gustavek commented
> so this is good to merge?

yes! thanks!

2020-04-21 12:30 UTC, merged